# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/similarity-learning',
                'doc_host': 'https://Irad-Zehavi.github.io',
                'git_url': 'https://github.com/Irad-Zehavi/similarity-learning',
                'lib_path': 'similarity_learning'},
  'syms': {'similarity_learning.core': {'similarity_learning.core.foo': ('core.html#foo', 'similarity_learning/core.py')}}}
